sudo: false

# Lightweight VM, because we install all the tools on our own.
language: c

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
    - libgmp-dev

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack config set system-ghc --global true

install:
  - travis_wait stack --no-terminal --install-ghc setup

script:
  - stack test